stages:
  - deploy

deploy_image:
  stage: deploy
  script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh user@mypatch.fr "cd portfolio && docker compose down && docker pull && docker compose up -d"
