services:
  frontend:
    container_name: frontend
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
    restart: always #change if you don't want your container restarting
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
