name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: kodelab.fr
          ssh_private_key: ${{ secrets.KODELAB_SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.KODELAB_SSH_USER }}
          docker_compose_prefix: briochePortfolio
